exports.BattlePokedex = {
	charmander: {
		inherit: true,
		types: ["Ground", "Fire"],
		classification: ["Gram+", "Cocci", "Coagulase+", "Catalase+", "HIV"],
		weaknesses: ["Penicinillase-Resistant Penicillin", "Glycopeptide"],
		microbe: "bacteria",
	},
	charmander: {
		inherit: true,
		types: ["Fire", "Steel"],
		classification: ["Gram+", "Cocci", "Coagulase+", "Catalase+", "HIV"],
		weaknesses: ["Glycopeptide"],
		microbe: "bacteria",
	},
	lickitung: {
		inherit: true,
		types: ["Flying"],
		classification: ["Gram+", "Cocci", "Catalase-", "a-hemolytic", "HIV"],
		weaknesses: ["Natural Penicillin", "Aminopenicillin", "3rd Gen Ceph", "Vancomycin"],
		microbe: "bacteria",
	},
	magmar: {
		inherit: true,
		types: ["Ground", "Fire"],
		classification: ["Gram+", "Cocci", "Catalase-", "LancefieldA"],
		weaknesses: ["Natural Penicillin", "Aminopenicillin", "Lincosamide"],
		microbe: "bacteria",
	},
	onix: {
		inherit: true,
		types: ["Rock", "Steel"],
		classification: ["Gram+", "Bacillus", "Obligate Anaerobe", "Spore-Forming", "Motile"],
		weaknesses:  ["Metronidazole", "Glycopeptide"],
		resistances: ["Clindamycin", "Aminopenicillin"],
		microbe: "bacteria",
	},
	jynx: {
		inherit: true,
		types: ["Grass", "Flying"],
		classification: ["Gram-", "Diplococci"],
		weaknesses: ["3rd Gen Ceph", "Macrolide"],
		microbe: "bacteria",
	},
	venusaur: {
		inherit: true,
		types: ["Flying", "Steel"],
		classification: ["Gram-", "Bacillus", "LactoseNF"],
		weaknesses: ["Carboxipenicillin", "Ureidopenicillin", "Aminoglycoside", "Fluoroquinolone", "Monobactam", "Carbapenem"],
		microbe: "bacteria",
	},
	ekans: {
		inherit: true,
		types: ["Water"],
		classification: ["Gram-", "Spirochete"],
		weaknesses: ["Natural Penicillin"],
		microbe: "bacteria",
	},
	ninetales: {
		inherit: true,
		types: ["Rock"],
		classification: ["Gram-", "Bacillus", "Urease+"],
		weaknesses: ["Aminopenicillin", "Macrolide", "Metronidazole", "Tetracyline"],
		microbe: "bacteria",
	},
	persian: {
		inherit: true,
		types: ["Ground", "Fire"],
		classification: ["Gram-", "Bacillus", "Cocci", "Coccobacillus"],
		weaknesses: ["Macrolide", "Tetracyline"],
		microbe: "bacteria",
	},
	dugtrio: {
		inherit: true,
		types: ["Ground", "Water"],
		classification: ["Gram-", "Bacillus", "Indole+"],
		weaknesses: ["TMP-SMX", "Penicillin", "3rd Gen Ceph"],
		microbe: "bacteria",
	},
	gloom: {
		inherit: true,
		types: ["Grass"],
		classification: [],
		weaknesses: ["Macrolide", "Tetracyline"],
		microbe: "bacteria",
	},
	golem: {
		inherit: true,
		types: ["Flying", "Steel"],
		classification: ["Acid-Fast", "HIV"],
		weaknesses: ["Rifampin", "RIPE"],
		microbe: "bacteria",
	},
	graveler: {
		inherit: true,
		types: ["Flying"],
		classification: ["Acid-Fast", "HIV"],
		weaknesses: ["Macrolide", "Rifampin", "Ethambutol"],
		microbe: "bacteria",
	},
	steelix: {
		inherit: true,
		classification: ["Gram+", "Catalase-"],
		types: ["Rock"],
		weaknesses: ["Aminopenicillin", "Glycopeptide", "Aminoglycoside"],
		microbe: "bacteria",
	},
	meowth: {
		inherit: true,
		classification: ["Protozoa", "HIV"],
		types: ["Electric"],
		weaknesses: ["TMP-SMX", "Lincosamide", "Anti-malarial"],
		microbe: "protozoa",
	},
	magikarp: {
		inherit: true,
		classification: ["Protozoa", "HIV"],
		types: ["Rock"],
		weaknesses: [],
		microbe: "protozoa",
	},
	weedle: {
		inherit: true,
		classification: ["Gram+", "Cocci"],
		types: ["Flying", "Electric"],
		weaknesses: ["Natural Penicillin", "Aminopenicillin"],
		microbe: "bacteria",
	},
	raticate: {
		inherit: true,
		classification: ["Gram-", "Cocci", "Bacillus", "Coccobacillus", "HIV"],
		types: ["Flying", "Electric"],
		weaknesses: ["3rd Gen Ceph"],
		microbe: "bacteria",
	},
	shellder: {
		inherit: true,
		classification: ["Gram-", "Bacillus", "HIV"],
		types: ["Rock"],
		weaknesses: ["3rd Gen Ceph", "Fluoroquinolone", "Aminopenicillin"],
		microbe: "bacteria",
	},
	muk: {
		inherit: true,
		classification: ["Gram-", "Bacillus", "HIV"],
		types: ["Rock"],
		weaknesses: ["Fluoroquinolone"],
		microbe: "bacteria",
	},
	pidgey: {
		inherit: true,
		classification: ["Gram-", "Bacillus", "HIV"],
		types: ["Rock"],
		weaknesses: ["Macrolide", "Fluoroquinolone"],
		microbe: "bacteria",
	},

	miltank: {
		inherit: true,
		types: ["Normal"],
	},
	unown: {
		inherit: true,
		types: ["Normal"],
	},
	dragonite: {
		inherit: true,
		types: ["Normal"],
	}
}
